[project]
name = "dspy-example"
version = "0.1.0"
description = "DSPy example"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "create-agent-app",
    "dspy>=3.0.4b1",
    "langwatch-scenario>=0.1.3",
    "pytest>=9.0.3",
    "python-dotenv>=1.2.2",
]

[tool.uv.sources]
create-agent-app = { path = "../", editable = true }
